In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Titanic_Unclean_Large.csv")

In [4]:
df.head()

   PassengerId         Name   Age     Sex  Pclass    Fare Embarked  Survived
0            1   Alex Smith  20.0  female       1  452.12      NaN         0
1            2   Alex Brown   NaN  female       2     NaN        Q         0
2            3  Sara Taylor  72.0     NaN       2     NaN      NaN         1
3            4  Mary Taylor   NaN  female       3     NaN      NaN         1
4            5   Mary Brown  21.0    male       3  174.39        C         1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  2000 non-null   int64
 1   Name         2000 non-null   object
 2   Age          980 non-null    float64
 3   Sex          1359 non-null   object
 4   Pclass       2000 non-null   int64
 5   Fare         970 non-null    float64
 6   Embarked     1512 non-null   object
 7   Survived     2000 non-null   int64
dtypes: float64(2), int64(3), object(3)
memory usage: 125.1+ KB

In [6]:
df.isnull().sum()

PassengerId       0
Name              0
Age            1020
Sex             641
Pclass            0
Fare           1030
Embarked        488
Survived          0
dtype: int64

In [7]:
df['Age'].fillna(df['Age'].median(), inplace=True)

/tmp/ipython-input-286566303.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

In [8]:
df['Fare'].fillna(df['Fare'].median(), inplace=True)

/tmp/ipython-input-146823877.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(df['Fare'].median(), inplace=True)

In [9]:
df['Sex'].fillna(df['Sex'].mode()[0], inplace=True)

/tmp/ipython-input-2715098637.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sex'].fillna(df['Sex'].mode()[0], inplace=True)

In [10]:
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

/tmp/ipython-input-411043493.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [11]:
df.isnull().sum()

PassengerId    0
Name           0
Age            0
Sex            0
Pclass         0
Fare           0
Embarked       0
Survived       0
dtype: int64

In [12]:
df.shape

(2000, 8)

In [13]:
df = df.drop_duplicates()

In [14]:
df.shape

(2000, 8)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  2000 non-null   int64
 1   Name         2000 non-null   object
 2   Age          2000 non-null   float64
 3   Sex          2000 non-null   object
 4   Pclass       2000 non-null   int64
 5   Fare         2000 non-null   float64
 6   Embarked     2000 non-null   object
 7   Survived     2000 non-null   int64
dtypes: float64(2), int64(3), object(3)
memory usage: 125.1+ KB

In [16]:
df['Age'] = df['Age'].astype(int)
df['Fare'] = df['Fare'].astype(float)

In [17]:
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[0, 12, 18, 60, 100],
    labels=['Child', 'Teen', 'Adult', 'Senior']
)

In [18]:
df['Fare_Category'] = pd.cut(
    df['Fare'],
    bins=[0, 50, 150, 300, 600],
    labels=['Low', 'Medium', 'High', 'Very High']
)

In [19]:
df['Survival_Status'] = df['Survived'].map({
    0: 'Not Survived',
    1: 'Survived'
})

In [20]:
df.to_csv("Titanic_Cleaned_Data.csv", index=False)

### Data Cleaning Summary
- Loaded Titanic dataset into Google Colab
- Identified missing values using isnull().sum()
- Filled numeric columns (Age, Fare) using median
- Filled categorical columns (Sex, Embarked) using mode
- Removed duplicate records
- Converted data types for accuracy
- Created new columns such as Age Group and Fare Category
- Saved cleaned dataset for further analysis